### PR TITLE
First pass at Substr impl

### LINKED ISSUE #6: Reference counted Substr
From README: Essentially an ergonomic `(ArcStr, Range<usize>)`, which can be used to
avoid allocation when creating a lot of ranges over the same string. A use
case for this is parsers and lexers (Note that in practice I might use
`Range<u32>` and not `Range<usize>`).

### PR DESCRIPTION
**Pull request by thomcc**
needs toplevel docs still and idk if ci will pass fully

fixes #6

### CODE REVIEW

**Comment by thomcc** [comment]
also should do Substr::as_static since it's tedious to do `substr.parent().as_static().map(|p|&p[substr.range()])` and we can skip that bounds check too.

**Comment by thomcc** [comment]
"Less unsafe" is kinda surprising, this crate has a bunch of unsafe. That said, i try to justify it with the fact that it also tests under:

- miri
- asan
- msan
- tsan
- loom

and on

- linux x86, x86_64, arm32, aarch64, mips64 (look it's the only big endian I could make cross run in CI)
- windows msvc and gnu (eventually 32-bit of these maybe but I'm not really worried)
- macos

and has nearly full test coverage.

**Comment by thomcc** [comment]
Also since you mention an Rc string: note that our use of atomic increments and decrements is required for stuff like const literals to work:

```rust
const THING: ArcStr = arcstr::literal!("foobar");
```

But really if you have perf issues on ARM or something a) that's really surprising and b) let me know, I've done a lot of optimization work on that platform. (On x86 the atomics should be basically the same speed as Rc)

**Comment by jyn514** [comment]
> it also tests under [lots of sanitizers]

Right, that's what I meant :) The other crate has a couple basic tests of the functionality but I don't think they even run miri: https://github.com/panicbit/shared_str/blob/master/src/shared_str.rs#L123

>  if you have perf issues on ARM or something a) that's really surprising and b) let me know,

`saltwater` is not in a sufficient state of functionality to worry about performance 😆 but if I run into issues I'll let you know.

**Comment by thomcc** [comment]
Okay, I see a few missing APIs from shared_str (well, sort of missing. we have equivalents, just awkwardly) and will try to add them later today after breakfast or whatever.

**Comment by jyn514** [comment]
The only ones saltwater really uses are `impl Deref<Target = str>` and `slice_with`. I see you have the Deref impl, so all we'd need is `slice_with` I think :)

**Comment by thomcc** [comment]
Yeah slice_with is basically ArcStr::try_substr_from but i should put that functionality on Substr too and it's easy enough to mirror the API. Not sure I like the name tbh, since it was extremely unclear to me what the hell it did

**Comment by hdamron17** [comment]
Yeah this looks like it covers everything we need for Saltwater (which like @jyn514 said is just substrings of `Rc<str>` with basic functionality like `PartialEq`).

**Comment by jyn514** [comment]
> Not sure I like the name tbh, since it was extremely unclear to me what the hell it did

Yeah I agree `substr_from` is much more clear.

**Comment by thomcc** [comment]
> Yeah I agree substr_from is much more clear.
Yeah, the API now is
```rust
// panic if not a substr
fn substr_from(&self, s: &str) -> Substr;
fn substr_using(&self, f: impl FnOnce(&str) -> &str) -> Substr;

// return none if not a substr
fn try_substr_from(&self, s: &str) -> Option<Substr>;
fn try_substr_using(&self, f: impl FnOnce(&str) -> &str) -> Option<Substr>;
```

On both `ArcStr` and `Substr`. No equivalent to the unchecked, that said the code as is does a few redundant tests although they should be correctly branch predicted. Didn't seem worth the extra unsafe, but if you see a perf. bottleneck in any of this LMK and there are low-hangling fruit.

**Comment by thomcc** [comment]
i still need to adjust module docs and readme because they all talk about my dreams of adding a second type into this crate, but as if they were far away goals that will be impossible to meet.

**Comment by jyn514** [comment]
Actually maybe `from_substr` is more consistent with how std names things? Then you'd have `try_from_substr` which reads a little nicer

**Comment by thomcc** [comment]
hmmm, sure. what about the other, still substr_using?

**Comment by jyn514** [comment]
I'd prefer `using_substr` for consistency, but I don't feel strongly about it.

**Comment by thomcc** [comment]
that feels wrong. i see why you say it using_substr feels more consistent, but on its own, without comparing to from_substr, it's extremely unintuitive as to what it does or what the argument it gives you is.

it implies that it's some kind of substring, either in terms of Substr static type, or in terms of not being the whole str.

e.g. it feels like the object of the verb "using" is "substr" there where as in reality the object of that verb is the fnonce, which is the thing that we are using to produce a substr.

this actually helps me articulate my slight hesitation for `from_substr` and `try_from_substr`: in `ArcStr::from_substr(&self, &str)` the result is a Substr, and which feels weird...

**Comment by jyn514** [comment]
Ahh, that makes sense - this substr is an _output_ and not an input. Ok yeah the original names seem fine then.

**Comment by thomcc** [comment]
i dont have the doc updates in me rn, i'm going to merge this and get them in tomorrow or something then do the 0.2.2.

i'd prefer to let it stew in my mind and maybe use in some of my code a bit via git dep. that would point out APIs which are obviously missing, as well as help catch any bugs that the testing managed to somehow dodge...

anyway a day or so ain't that bad, and really i suspect that even if you wanted to switch super urgently or w/e, it would take a bit anyway and could be done in a branch with a git dep.

anyway, will file followup for doc update and release cut after merging this.

**Pull request merged**
